clear

% Run ibpm from matlab
name = 'base_';
outdir = '.';
tecplot = 0;
restart = 1;
force = 0;
nx = 300;
ny = 300;
ngrid = 1;
length = 6;
xoffset = -1;
yoffset = -3;
geom = 'plate4.geom';
ubf = 1;
Re = 100;
model = 'nonlinear';
dt = 0.01;
nsteps = 200;

command = ['./plunging2',...
    ' -name ',name,...
    ' -outdir ',outdir,...
    ' -tecplot ',num2str(tecplot),...
    ' -restart ',num2str(restart),...
    ' -force ',num2str(force),...
    ' -nx ',num2str(nx),...
    ' -ny ',num2str(ny),...
    ' -ngrid ',num2str(ngrid),...
    ' -length ',num2str(length),...
    ' -xoffset ',num2str(xoffset),...
    ' -yoffset ',num2str(yoffset),...
    ' -geom ',num2str(geom),...
    ' -ubf ',num2str(ubf),...
    ' -Re ',num2str(Re),...
    ' -model ',num2str(model),...
    ' -dt ',num2str(dt),...
    ' -nsteps ',num2str(nsteps)];

system(command)
